#!/bin/sh

: ${EVM:=evm}

tmp=$(mktemp -d)

trap 'rm -rf "$tmp"' EXIT

if [ $# = 0 ]; then
	set -- test/*
fi

failed=0

for test; do
	pass=0
	echo "Running test $test..."
	echo
	. "$test"
	printf ' %s %s %s %s\n' $output >"$tmp/want"
	input="$(printf %064x $redex)$(printf %s $input)"
	if $EVM --statdump --input "$input" --codefile net.evm run >"$tmp/out"; then
		tail -c +67 "$tmp/out" | sed '
			s,[[:xdigit:]]\{32\},&\n,g
			s,[[:xdigit:]]\{8\}, &,g
		' | sed '$d' >"$tmp/got"
		if (cd "$tmp" && diff -u got want); then
			printf 'PASS (used %d gas)\n' "$(head -c 66 "$tmp/out")"
			pass=1
		fi
	fi
	if [ "$pass" -eq 0 ]; then
		failed=$((failed + 1))
		printf "\nFAIL\n"
	fi
	echo "--------------------------------------------------------------------------------"
done

echo "$failed test failures"
[ "$failed" -eq 0 ]
